#!/usr/bin/env bash
set -euo pipefail

# Best-effort v1 -> v2 Copilot FinOps config converter.
#
# Reads a v1 budget-policies file and/or a v1 cost-center-members file and emits the
# merged v2 config (config/copilot-finops.yml shape) on stdout, applying the v1 -> v2
# rename map (see schemas/README.md). v1 stays frozen; this is a one-shot migration aid.
#
#   scripts/migrate-v1-to-v2.sh --budgets config/budget-policies.yml \
#                               --members config/cost-center-members.yml \
#                               --output config/copilot-finops.yml
#
# ALWAYS review and validate the result before using it:
#   scripts/validate-config.sh <output> all
#
# Notes:
# - At least one of --budgets / --members is required.
# - Enterprise slug precedence: --enterprise-slug > budgets file > members file.
# - The converter preserves explicit stop_at_limit (prevent_further_usage) and
#   remove_extra_members values; omitted ones fall back to the v2 defaults.

BUDGETS_FILE=""
MEMBERS_FILE=""
OUTPUT_FILE=""
ENTERPRISE_SLUG_CLI=""

usage() {
  cat >&2 <<'EOF'
Usage: scripts/migrate-v1-to-v2.sh [--budgets <v1-budgets.yml>] [--members <v1-members.yml>]
                                   [--enterprise-slug <slug>] [--output <file>]

At least one of --budgets / --members is required. Output goes to stdout unless --output is given.
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --budgets)
      BUDGETS_FILE="$2"
      shift 2
      ;;
    --members)
      MEMBERS_FILE="$2"
      shift 2
      ;;
    --enterprise-slug)
      ENTERPRISE_SLUG_CLI="$2"
      shift 2
      ;;
    --output)
      OUTPUT_FILE="$2"
      shift 2
      ;;
    -h | --help)
      usage
      exit 0
      ;;
    *)
      echo "ERROR: unknown argument: $1" >&2
      usage
      exit 1
      ;;
  esac
done

if [[ -z "$BUDGETS_FILE" && -z "$MEMBERS_FILE" ]]; then
  echo "ERROR: at least one of --budgets / --members is required." >&2
  usage
  exit 1
fi
if ! command -v yq >/dev/null 2>&1; then
  echo "ERROR: yq is required." >&2
  exit 1
fi
for f in "$BUDGETS_FILE" "$MEMBERS_FILE"; do
  if [[ -n "$f" && ! -f "$f" ]]; then
    echo "ERROR: file does not exist: $f" >&2
    exit 1
  fi
done

# Enterprise slug: CLI > budgets file > members file.
enterprise_slug="$ENTERPRISE_SLUG_CLI"
if [[ -z "$enterprise_slug" && -n "$BUDGETS_FILE" ]]; then
  enterprise_slug="$(yq eval '.enterprise_slug // ""' "$BUDGETS_FILE")"
fi
if [[ -z "$enterprise_slug" && -n "$MEMBERS_FILE" ]]; then
  enterprise_slug="$(yq eval '.enterprise_slug // ""' "$MEMBERS_FILE")"
fi

# Transform v1 budget_policies[] -> v2 ai_credit_spend_policies[]. Builds each policy with
# direct renames (carrying a few temp _fields), derives credit_scope/alert_admins via
# conditional updates, then drops temp keys and any null/absent fields.
budgets_block='ai_credit_spend_policies: []'
if [[ -n "$BUDGETS_FILE" ]]; then
  budgets_block="$(yq eval '
    {"ai_credit_spend_policies": (
      (.budget_policies // []) | map({
        "name": .name,
        "description": .description,
        "scope": (.type | sub("^universal$", "all_users")),
        "enterprise": .source.enterprise,
        "organization": .source.org,
        "teams": null,
        "cost_center": .target.cost_center,
        "credit_scope": null,
        "amount": .budget.amount,
        "stop_at_limit": .budget.prevent_further_usage,
        "alert_admins": null,
        "_type": .type,
        "_coverage": .coverage,
        "_team_slug": .source.team_slug,
        "_will_alert": .budget.alerting.will_alert,
        "_recipients": .budget.alerting.alert_recipients
      })
      | (.[] | select(._type == "team")) |= (.teams = [._team_slug] | .credit_scope = ((._coverage // "total_spend") | sub("^total_spend$", "pool_then_metered") | sub("^additional_spend$", "metered_only")))
      | (.[] | select(._will_alert == true and ((._recipients // []) | length) > 0)) |= (.alert_admins = ._recipients)
      | map(del(._type) | del(._coverage) | del(._team_slug) | del(._will_alert) | del(._recipients))
      | map(with_entries(select(.value != null)))
    )}
  ' "$BUDGETS_FILE")"
fi

# Transform v1 mappings[] -> v2 team_cost_center_mappings[].
members_block='team_cost_center_mappings: []'
if [[ -n "$MEMBERS_FILE" ]]; then
  members_block="$(yq eval '
    {"team_cost_center_mappings": (
      (.mappings // []) | map({
        "name": .name,
        "description": .description,
        "enterprise": .source.enterprise,
        "organization": .source.org,
        "team": .source.team_slug,
        "cost_center": .target.cost_center,
        "remove_extra_members": .sync.remove_extra_members
      } | with_entries(select(.value != null)))
    )}
  ' "$MEMBERS_FILE")"
fi

# Assemble the merged v2 document and normalize via yq.
{
  echo "# Generated by scripts/migrate-v1-to-v2.sh. Review and validate before use:"
  echo "#   scripts/validate-config.sh <this-file> all"
  echo "version: 2"
  if [[ -n "$enterprise_slug" ]]; then
    printf 'enterprise_slug: %s\n' "$enterprise_slug"
  fi
  echo "$budgets_block"
  echo "$members_block"
} | yq eval '.' - >"${OUTPUT_FILE:-/dev/stdout}"

if [[ -z "$enterprise_slug" ]]; then
  echo "WARNING: no enterprise_slug resolved; set it in the output or pass --enterprise-slug / a workflow input." >&2
fi
if [[ -n "$OUTPUT_FILE" ]]; then
  echo "Wrote $OUTPUT_FILE. Validate it with: scripts/validate-config.sh $OUTPUT_FILE all" >&2
fi
